Bump libhunspell-dev version.
Building thunderbird in stretch, against hunspell 1.4, leads to these
errors because of missing functions in its API:
| error: 'class Hunspell' has no member named 'get_dict_encoding'
| error: no matching function for call to 'Hunspell::spell(std::__cxx11::string&)'
| error: no matching function for call to 'Hunspell::suggest(std::__cxx11::string&)'

These functions were added in 1.5.1, so the upstream configure scripts
should probably check for it as a minimal version.